/************************************************************************************************
 * Terms of Service Page:

 * This file defines the server-rendered page for displaying ShapeShift's Terms of Service.
 * It fetches the terms of service content using `getTermsOfServiceItems` and renders it
 * using the reusable `TermsPage` component.

 * Metadata for this page (title, description, OpenGraph tags) is generated by the
 * `generateMetadata` function from `TermsPage`, ensuring consistency with other
 * legal documents.
 ************************************************************************************************/

import {notFound} from 'next/navigation';

import {TermsPage, generateMetadata} from '@/app/(terms)/_components/TermsPage';
import {getTermsOfServiceItems} from '@/app/(terms)/_components/utils';

import type {Metadata} from 'next';
import type {ReactNode} from 'react';

/************************************************************************************************
 * metadata Constant:

 * Exports the metadata for the Terms of Service page.
 * It calls `generateMetadata` with the title "Terms of Service" to create SEO-friendly
 * and socially shareable metadata.
 ************************************************************************************************/
export const metadata: Metadata = generateMetadata({title: 'Terms of Service'});

/************************************************************************************************
 * TermsOfServicePage Function Component (Async):

 * The main server component responsible for fetching and rendering the Terms of Service page.

 * Behavior:
 * - Asynchronously fetches terms of service items using `getTermsOfServiceItems`.
 * - If no items are found, it triggers a `notFound()` response (404 page).
 * - Otherwise, it renders the `TermsPage` component, passing the title "Terms of Service"
 *   and the fetched items.

 * Returns:
 * - A Promise that resolves to the ReactNode representing the rendered Terms of Service page
 *   or a 404 page if content is not available.
 ************************************************************************************************/
export default async function TermsOfServicePage(): Promise<ReactNode> {
	const items = await getTermsOfServiceItems();

	if (!items.length) {
		return notFound();
	}

	return (
		<TermsPage
			title={'Terms of Service'}
			items={items}
		/>
	);
}
